package corba;


/**
* corba/EchoService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Wednesday, November 23, 2022 6:44:00 PM COT
*/

public interface EchoService extends EchoServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EchoService
